pyenchant/pyenchant

enchant/tokenize/__init__.py
website/content/tutorial.rst

Two small documentation fixes

---

enchant/__init__.py

Fix TypeError at shutdown.

---

enchant/checker/GtkSpellCheckerDialog.py

Looks like this was introduced by e017e62f

Fix unescaped quote mark

---

enchant/checker/CmdLineChecker.py

Hey Ryan!
I added some coloring functions and some other things to make the output of this script pop a bit :).
Most of the choices I made were purely aesthetic on my end so I'm up to change around some of that if it is deemed ugly lol. Let me know what you think!

Adding context and colors to CmdLineChecker

---

website/content/tutorial.rst

Just bumped into this typo while cut&pasting ;)

Typo fix in tutorial

---

enchant/__init__.py
enchant/tests.py
setup.py

@halfak could you please try this out and let me know if it fixes #88 for you?

Fix handling of NULL param values in python3

---

enchant/__init__.py
enchant/_enchant.py
enchant/pypwl.py

Remove is_in_session of which the function is removed in Enchant 2.0 and
was already deprecated.

Add enchant 2 compatibility

---

.github/workflows/linters.yml
enchant/__init__.py
enchant/_enchant.py
enchant/checker/GtkSpellCheckerDialog.py
enchant/checker/__init__.py
enchant/checker/wxSpellCheckerDialog.py
enchant/pypwl.py
enchant/tokenize/__init__.py
enchant/tokenize/en.py
enchant/utils.py
setup.cfg
tests/test_broker.py
tests/test_checker.py
tests/test_dict.py
tests/test_pwl.py
tests/test_tokenize.py
tools/shootout.py
tox.ini

* Fix some styling issues not found by black
* Remove all star imports

Run flake8 on all the code

---

enchant/__init__.py
enchant/_enchant.py
enchant/checker/__init__.py
enchant/pypwl.py
enchant/tokenize/__init__.py
enchant/tokenize/en.py
enchant/utils.py
setup.cfg
tests/test_broker.py
tests/test_dict.py
tests/test_docstrings.py
tests/test_pwl.py
tests/test_tokenize.py
tox.ini

Conform to PEP8 naming

---

.github/workflows/tests.yml
.gitignore
bootstrap.py
enchant/_enchant.py
enchant/checker/__init__.py
tests/test_checker.py
tests/test_pwl.py
tox.ini
website/content/install.rst
website/content/tutorial.rst

Restore Windows support

---

enchant/__init__.py
enchant/_enchant.py
release.py
tests/test_broker.py
tests/test_docstrings.py

Fix get param error

---

bootstrap.py

Licenses in wheels

---

enchant/__init__.py
enchant/_enchant.py
tests/test_broker.py
tests/test_misc.py
tests/test_multiprocessing.py
tox.ini
website/content/changelog.rst

Implement get_user_config_dir, plus a few fixes

---

enchant/__init__.py
tests/test_checker.py
tests/test_dict.py
tests/test_docstrings.py

allow 'plugins' for the set_prefix_dir() docstring

---

.github/workflows/linters.yml
.github/workflows/tests.yml
.github/workflows/website.yml

Just because I don't like depending on old stuff for CI

Actions: Bump checkout, setup-python

---

website/content/install.rst

doc: Add a paragraph about MacPorts

---

.github/workflows/tests.yml

CI: ne-enable pypy3 on Windows

---

.github/workflows/tests.yml
setup.cfg
tox.ini
website/content/changelog.rst

Python 3.9 was released on October 5th, 2020.

Add testing and document support for Python 3.9

---

enchant/__init__.py

Make broker destructor less picky

---

bootstrap.py
enchant/__init__.py
enchant/checker/GtkSpellCheckerDialog.py
release.py
tests/test_tokenize.py
tox.ini

Bump black

---

website/content/install.rst

@dmerejkowsky , I created this PR to solve #281 .
Can you please review?
I have the feeling that the MacOS section is quite big right now.
@undo76, can you have a look at the new doc and give a feedback?

Update Apple Silicon installation in install.rst

---

enchant/tokenize/de.py

Thanks for the pyenchant project. It helps me a lot with spell check in various Sphinx projects.
With this pull request I suggest a tokenizer for German. The tokenizer is based on the existing tokenizer for English. It adds `-` and `.` to the valid characters list.
With this tokenizer the spell checking works a lot better and saves me some additional work and maintaining some weird dictionaries.
I would love to have this tokenizer included in the project, so I can drop my local implementation as part of a Sphinx extensions.
Thanks.

Add tokenizer for German language

---

bootstrap.py

Note: AppVeyor and GitHub actions used different suffixes, so also introduce a `get_bits() -> int` function to simplify things

bootstrap: use archive generated from GitHub Actions

---

.github/workflows/linters.yml
.github/workflows/tests.yml
.github/workflows/website.yml
enchant/__init__.py
enchant/_enchant.py
enchant/checker/CmdLineChecker.py
enchant/checker/wxSpellCheckerDialog.py
enchant/tokenize/__init__.py
enchant/tokenize/de.py
enchant/tokenize/en.py
tests/test_broker.py
tests/test_checker.py
tests/test_dict.py
tests/test_pwl.py
tests/test_tokenize.py
tools/shootout.py
tox.ini

* Bump Python versions
* Update GitHub Actions
* Fix compatibility with Enchant > 2.5 (#313)
* Bump all linters

Big updates
