pyenchant/pyenchant

.gitignore
enchant/__init__.py
enchant/utils.py

...by filtering chars before passing words to enchant.
This change is meant to address See https://github.com/rfk/pyenchant/issues/58
I didn't see a clear place to add a test, so here's a demo of the fix on the CLI.  
**$ python3**
```
Python 3.4.0 (default, Apr 11 2014, 13:05:11) 
[GCC 4.8.2] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import enchant
>>> d = enchant.Dict("en")
>>> d.check("test")
True
>>> d.check(chr(2**16))
False
```
**$ python2**
```
Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import enchant
>>> d = enchant.Dict("en")
>>> d.check("test")
True
>>> d.check(unichr(2**16).encode('utf8'))
False
```

Silences UTF16 encoding warning 

---

enchant/tokenize/__init__.py

Fixes `DeprecationWarning: invalid escape sequence` with Python 3.6.
Found using [pydiatra](https://github.com/jwilk/pydiatra).

Make docstrings that contain regexps raw

---

website/content/download.html
website/content/tutorial.rst

As per [their blog post of the 27th April](https://blog.readthedocs.com/securing-subdomains/) ‘Securing subdomains’:
> Starting today, Read the Docs will start hosting projects from subdomains on the domain readthedocs.io, instead of on readthedocs.org. This change addresses some security concerns around site cookies while hosting user generated data on the same domain as our dashboard.
Test Plan: Manually visited all the links I’ve modified.

Convert readthedocs links for their .org -> .io migration for hosted projects

---

enchant/tokenize/en.py
enchant/tokenize/tests.py

I implemented a fix that might be suboptimal.
I tried adding the typographic apostrophe to the `valid_chars` of the English tokenizer's initialization function, but this didn't lead to the desired results. Afterwards, the spell checker didn't recognize any words with a typographic apostrophe.

support typographic apostrophes #93

---

enchant/_enchant.py

After support for enchant2 is already merged, the only thing missing is to detect the library :)
I am aware that you are no longer maintaining this, so feel no pressure to merge or even release this. But having this pull request here might help people to find out why this isn't running on Arch Linux currently and can discover the workaround of installing this fork:
``pip install git+https://github.com/raphaelm/pyenchant.git@patch-1#egg=pyenchant``

Auto-detect enchant2

---

README.rst

For 3.0.x there are not binary wheels published for macOS.

Update macOS install notes

---

website/content/install.rst

This PR adds a note to the documentation on [ctypes' find_library external dependencies](https://docs.python.org/3/library/ctypes.html#finding-shared-libraries). These have to installed manually on some (container) distributions like alpine linux.

Add exernal ctypes.util.find_library dependencies to documentation

---

enchant/_enchant.py

windows: set PATH instead of calling SetDllDirectory

---

website/content/tutorial.rst

Since 36930b55ac9881445a262a355af74c83ceef28e1, the filters argument is
expected to be a keyword argument.

Use filters keyword argument for get_tokenizer() in docs

---

setup.cfg

The trove classifiers now accurately document that pyenchant is Python 3
only, the specific Python versions supported, and that the PyPy
platform is supported.
These classifiers help new users know, at a quick glance, what is
supported by the library without digging into the docs or README.
These classifiers are also used by scripts and tools for some
automation.
For a complete list of trove classifiers, see:
https://pypi.org/classifiers/

Add trove classifiers for all supported Python versions

---

.github/workflows/tests.yml

There's a bug in pypy that prevents tox from working
https://foss.heptapod.net/pypy/pypy/-/issues/3331
Closes #218

CI: disable pypy3 on Windows

---

enchant/__init__.py
enchant/checker/CmdLineChecker.py
enchant/checker/GtkSpellCheckerDialog.py
enchant/checker/wxSpellCheckerDialog.py
enchant/pypwl.py
enchant/tokenize/__init__.py
enchant/tokenize/en.py
website/conf.py

pyupgrade is a tool to automatically upgrade syntax for newer versions
of the Python language. For details, see:
https://github.com/asottile/pyupgrade
As the project is Python 3 only, this tools applies several
simplifications:
- No longer need to specify Python file encoding. Python files are read
as utf-8 by default.
- No longer need to prefix Unicode strings with u. Python 3 strings are
Unicode by default.
- No longer need to inherit from object as Python 3 removed the legacy
old-style classes.
- Use shorter Python 3 super() syntax.
- Remove __future__ imports that are no longer necessary.

Run pyupgrade across the codebase

---

tests/test_tokenize.py

There is a small typo in tests/test_tokenize.py.
Should read `tokenizing` rather than `tokeniting`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md

docs: fix simple typo, tokeniting -> tokenizing

---

enchant/__init__.py
enchant/checker/__init__.py
tests/test_checker.py
tests/test_misc.py
tests/test_multiprocessing.py
tests/test_tokenize.py
tox.ini

While working on https://github.com/pyenchant/pyenchant/pull/255 I found several small issues when testing locally.
- f3dff22 ci: skip_missing_interpreters
- 04d3c45 ci: Also drop Python 3.5 and 3.6 from tox
- e3b00d1 style[test]: Simplify test case
- ca07241 style[checker]: Simplify boolean logic
- 389c6d7 test[checker]: Use invalid word for HTML tag
- c63e5e4 test[checker]: Split test in 3
- 1f47238 test[multiproc]: Assert on all()
- e19934a test[misc]: Assert get_user_config_dir()
- 21885ac style[enchant]: Simplify Error raising

Cleanup from before PEP 484 type annotations

---

enchant/__init__.py
enchant/checker/CmdLineChecker.py
enchant/checker/__init__.py
enchant/checker/wxSpellCheckerDialog.py
enchant/pypwl.py
enchant/tokenize/__init__.py
enchant/tokenize/en.py
enchant/utils.py
tests/test_docstrings.py
website/content/api/enchant.errors.rst
website/content/api/index.rst
website/content/tutorial.rst

Improve the Sphinx generated documentation by providing direct links to API.
- cf9b661 doc: Convert to Sphinx reStructuredText
- 54bc8b0 doc[utils]: Add Wikipedia link for Levenshtein
- d3c5c81 doc[tutorial]: Convert to Python 3 print function
- a951a8c doc: Add enchant.errors

Improve documentation

---

LICENSE.txt

This is to match https://www.gnu.org/licenses/old-licenses/lgpl-2.1.txt because FSF moved to new address many years ago.

Update FSF address in LICENSE.txt

---

.github/workflows/tests.yml
.gitignore
enchant/_enchant.py
setup.cfg
tox.ini
website/content/install.rst

#265 added documentation for how to work around the change in location of Homebrew on M1 Macs. 
This PR removes the need for that workaround, by explicitly adding the Homebrew path to the list of lookup locations.
It also adds Python 3.11 and Python3.12 prereleases to the CI matrix.

Add support for detecting Homebrew on M1

---

tools/shootout.py
website/content/shootout.rst

Ispell and MySpell are obsolete, so compare Hunspell and Nuspell instead.

Update provider shootout

---

website/content/faq.rst

I just found an itsy bitsy tiny typo in the FAQ :)

fix typo in faq

---

README.rst

Update README.rst to link to the Enchant website's new location
